const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PRE_COMMIT_HOOK = `#!/bin/sh
# Generated by hugo-validator
# To regenerate: npx hugo-validator setup-hooks

npx hugo-validator validate

exit $?
`;

/**
 * Set up git pre-commit hooks
 */
async function setupHooks(options = {}) {
  const projectRoot = process.cwd();
  const hooksDir = path.join(projectRoot, '.githooks');
  const hookPath = path.join(hooksDir, 'pre-commit');

  // Check if this is a git repository
  const gitDir = path.join(projectRoot, '.git');
  if (!fs.existsSync(gitDir)) {
    console.log('\u26A0\uFE0F  Not a git repository - skipping hooks setup');
    return;
  }

  // Create .githooks directory
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // Create pre-commit hook
  if (fs.existsSync(hookPath) && !options.force) {
    console.log('\u2139\uFE0F  .githooks/pre-commit already exists (use --force to overwrite)');
  } else {
    fs.writeFileSync(hookPath, PRE_COMMIT_HOOK);
    fs.chmodSync(hookPath, '755');
    console.log('\u2705 Created .githooks/pre-commit');
  }

  // Configure git to use .githooks directory
  try {
    const currentHooksPath = execSync('git config --get core.hooksPath 2>/dev/null', {
      encoding: 'utf8',
      cwd: projectRoot,
    }).trim();

    if (currentHooksPath === '.githooks') {
      console.log('\u2139\uFE0F  Git hooks path already configured');
    } else {
      execSync('git config core.hooksPath .githooks', { cwd: projectRoot });
      console.log('\u2705 Configured git to use .githooks directory');
    }
  } catch {
    // core.hooksPath not set, set it now
    execSync('git config core.hooksPath .githooks', { cwd: projectRoot });
    console.log('\u2705 Configured git to use .githooks directory');
  }
}

module.exports = { setupHooks };
