const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Path of the locally installed executable, relative to the repository root
// (git runs hooks from there, which is where a site's node_modules lives).
const LOCAL_BIN = 'node_modules/.bin/hugo-validator';

const PRE_COMMIT_HOOK = `#!/bin/sh
# Generated by hugo-validator
# To regenerate: npx --no hugo-validator setup-hooks --force

# Runs the locally installed hugo-validator directly. It deliberately does not
# go through the npm package runner: without a local install, that would ask
# the npm registry for a package named hugo-validator, and this project is
# distributed from GitHub only. The registry name is not ours.
BIN="${LOCAL_BIN}"
if [ ! -x "$BIN" ]; then
  echo "hugo-validator is not installed in this project. Run: npm ci" >&2
  exit 1
fi

# --full: a commit is always gated by a complete run, never by cached results
"$BIN" validate --full
exit $?
`;

/**
 * Can this hook text reach the npm registry? True for hooks written by older
 * versions, which called the package runner without --no.
 */
function hookUsesRegistryNpx(hookText) {
  return /\bnpx\s+(?!--no\b)\S*hugo-validator/.test(
    String(hookText).split('\n').filter(line => !line.trim().startsWith('#')).join('\n')
  );
}

/**
 * Set up git pre-commit hooks
 */
async function setupHooks(options = {}) {
  const projectRoot = process.cwd();
  const hooksDir = path.join(projectRoot, '.githooks');
  const hookPath = path.join(hooksDir, 'pre-commit');

  // Check if this is a git repository
  const gitDir = path.join(projectRoot, '.git');
  if (!fs.existsSync(gitDir)) {
    console.log('\u26A0\uFE0F  Not a git repository - skipping hooks setup');
    return;
  }

  // Create .githooks directory
  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  // Create pre-commit hook
  if (fs.existsSync(hookPath) && !options.force) {
    console.log('\u2139\uFE0F  .githooks/pre-commit already exists (use --force to overwrite)');
  } else {
    fs.writeFileSync(hookPath, PRE_COMMIT_HOOK);
    fs.chmodSync(hookPath, '755');
    console.log('\u2705 Created .githooks/pre-commit');
  }

  // Configure git to use .githooks directory
  let currentHooksPath = '';
  try {
    currentHooksPath = execSync('git config --get core.hooksPath', {
      encoding: 'utf8',
      cwd: projectRoot,
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    // core.hooksPath not set
  }

  if (currentHooksPath === '.githooks') {
    console.log('ℹ️  Git hooks path already configured');
  } else if (currentHooksPath && !options.force) {
    // Another tool (Husky, lefthook, ...) owns the hooks path. Do not take it over silently.
    console.log(`⚠️  core.hooksPath is already set to '${currentHooksPath}' - leaving it unchanged`);
    console.log(`   Call '${LOCAL_BIN} validate --full' from your existing pre-commit hook,`);
    console.log('   or re-run with --force to point git at .githooks instead');
  } else {
    execSync('git config core.hooksPath .githooks', { cwd: projectRoot });
    console.log('✅ Configured git to use .githooks directory');
  }
}

module.exports = { setupHooks, hookUsesRegistryNpx, PRE_COMMIT_HOOK, LOCAL_BIN };
