// The Playwright tests and their config are owned by this package. They are
// copied into the site at run time, into a gitignored folder, so a site never
// commits test code and always runs the tests of the installed package version.
//
// They are copied rather than run from node_modules because neither Playwright
// nor Node compiles TypeScript that lives inside node_modules.
const fs = require('fs');
const path = require('path');
const { VALIDATOR_DIR } = require('./config');

const RUNTIME_DIR = path.join(VALIDATOR_DIR, '.runtime');
const PACKAGE_ROOT = path.join(__dirname, '..');
const PACKAGE_TESTS_DIR = path.join(PACKAGE_ROOT, 'tests');

function runtimePaths(projectRoot = process.cwd()) {
  const runtimeDir = path.join(projectRoot, RUNTIME_DIR);
  return {
    runtimeDir,
    testsDir: path.join(runtimeDir, 'tests'),
    configPath: path.join(runtimeDir, 'playwright.config.ts'),
    // Relative, for display and for passing to the Playwright CLI
    configArg: path.join(RUNTIME_DIR, 'playwright.config.ts'),
    resultsPath: path.join(runtimeDir, 'test-results', 'results.json'),
  };
}

/**
 * Command that serves public/ during the tests.
 * A user testServerCommand runs from <site>/hugo-validator, as it always has.
 */
function resolveServerCommand(config, projectRoot) {
  if (config.testServerCommand) return config.testServerCommand;
  const serveScript = path.join(PACKAGE_ROOT, 'lib', 'serve.js');
  const publicDir = path.join(projectRoot, 'public');
  return `node ${JSON.stringify(serveScript)} --port ${config.testServerPort} --dir ${JSON.stringify(publicDir)}`;
}

function resolveBrowserExecutable(config, env = process.env) {
  return env.HUGO_VALIDATOR_BROWSER || config.browserExecutable || null;
}

/**
 * Generated Playwright config. Values are baked in because the file is
 * rewritten on every run.
 */
function renderPlaywrightConfig(config, projectRoot, env = process.env) {
  const port = parseInt(config.testServerPort, 10) || 3000;
  const browserExecutable = resolveBrowserExecutable(config, env);
  const launchOptions = browserExecutable
    ? `\n    launchOptions: { executablePath: ${JSON.stringify(browserExecutable)} },`
    : '';

  return `// GENERATED by hugo-validator on every run. Do not edit: changes are overwritten.
// Settings come from hugo-validator/hugo-validator.config.js.
import { defineConfig, devices } from '@playwright/test';

const BASE_URL = 'http://localhost:${port}';

export default defineConfig({
  testDir: './tests',
  outputDir: './test-results',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['./tests/summary-reporter.ts']],
  use: {
    baseURL: BASE_URL,
    trace: 'off',
    screenshot: 'off',
    video: 'off',${launchOptions}
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: {
    command: ${JSON.stringify(resolveServerCommand({ ...config, testServerPort: port }, projectRoot))},
    cwd: ${JSON.stringify(path.join(projectRoot, VALIDATOR_DIR))},
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 60000,
    stdout: 'ignore',
    stderr: 'ignore',
  },
});
`;
}

/**
 * Sync tests and config into <site>/hugo-validator/.runtime.
 * test-results/ is left alone so --last-failed keeps working.
 */
function prepareRuntime(config, projectRoot = process.cwd(), env = process.env) {
  const paths = runtimePaths(projectRoot);

  fs.mkdirSync(paths.testsDir, { recursive: true });

  // Replace the tests wholesale so files removed from the package disappear
  for (const file of fs.readdirSync(paths.testsDir)) {
    fs.rmSync(path.join(paths.testsDir, file), { recursive: true, force: true });
  }
  const testFiles = fs.readdirSync(PACKAGE_TESTS_DIR).filter(file => file.endsWith('.ts'));
  for (const file of testFiles) {
    fs.copyFileSync(path.join(PACKAGE_TESTS_DIR, file), path.join(paths.testsDir, file));
  }

  fs.writeFileSync(paths.configPath, renderPlaywrightConfig(config, projectRoot, env));

  return { ...paths, testFiles };
}

module.exports = {
  prepareRuntime,
  runtimePaths,
  renderPlaywrightConfig,
  resolveServerCommand,
  resolveBrowserExecutable,
  RUNTIME_DIR,
  PACKAGE_TESTS_DIR,
};
