// The Playwright tests and their config are owned by this package. They are
// copied into the site at run time, into a gitignored folder, so a site never
// commits test code and always runs the tests of the installed package version.
//
// They are copied rather than run from node_modules because neither Playwright
// nor Node compiles TypeScript that lives inside node_modules.
const fs = require('fs');
const path = require('path');
const { VALIDATOR_DIR } = require('./config');

const RUNTIME_DIR = path.join(VALIDATOR_DIR, '.runtime');
const PACKAGE_ROOT = path.join(__dirname, '..');
const PACKAGE_TESTS_DIR = path.join(PACKAGE_ROOT, 'tests');

function runtimePaths(projectRoot = process.cwd()) {
  const runtimeDir = path.join(projectRoot, RUNTIME_DIR);
  return {
    runtimeDir,
    testsDir: path.join(runtimeDir, 'tests'),
    configPath: path.join(runtimeDir, 'playwright.config.ts'),
    // Relative, for display and for passing to the Playwright CLI
    configArg: path.join(RUNTIME_DIR, 'playwright.config.ts'),
    resultsPath: path.join(runtimeDir, 'test-results', 'results.json'),
  };
}

/**
 * Command that serves public/ during the tests.
 * A user testServerCommand runs from <site>/hugo-validator, as it always has.
 */
function resolveServerCommand(config, projectRoot) {
  if (config.testServerCommand) return config.testServerCommand;
  const serveScript = path.join(PACKAGE_ROOT, 'lib', 'serve.js');
  const publicDir = path.join(projectRoot, 'public');
  return `node ${JSON.stringify(serveScript)} --port ${config.testServerPort} --dir ${JSON.stringify(publicDir)}`;
}

function resolveBrowserExecutable(config, env = process.env) {
  return env.HUGO_VALIDATOR_BROWSER || config.browserExecutable || null;
}

/**
 * Generated Playwright config. Values are baked in because the file is
 * rewritten on every run.
 */
function renderPlaywrightConfig(config, projectRoot, env = process.env) {
  const port = parseInt(config.testServerPort, 10) || 3000;
  const browserExecutable = resolveBrowserExecutable(config, env);
  const launchOptions = browserExecutable
    ? `\n    launchOptions: { executablePath: ${JSON.stringify(browserExecutable)} },`
    : '';

  return `// GENERATED by hugo-validator on every run. Do not edit: changes are overwritten.
// Settings come from hugo-validator/hugo-validator.config.js.
import { defineConfig, devices } from '@playwright/test';

const BASE_URL = 'http://localhost:${port}';

export default defineConfig({
  testDir: './tests',
  outputDir: './test-results',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['./tests/summary-reporter.ts']],
  use: {
    baseURL: BASE_URL,
    trace: 'off',
    screenshot: 'off',
    video: 'off',${launchOptions}
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: {
    command: ${JSON.stringify(resolveServerCommand({ ...config, testServerPort: port }, projectRoot))},
    cwd: ${JSON.stringify(path.join(projectRoot, VALIDATOR_DIR))},
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 60000,
    stdout: 'ignore',
    stderr: 'ignore',
  },
});
`;
}

/**
 * Sync tests and config into <site>/hugo-validator/.runtime.
 * test-results/ is left alone so --last-failed keeps working.
 */
function prepareRuntime(config, projectRoot = process.cwd(), env = process.env) {
  const paths = runtimePaths(projectRoot);

  fs.mkdirSync(paths.testsDir, { recursive: true });

  // Replace the tests wholesale so files removed from the package disappear
  for (const file of fs.readdirSync(paths.testsDir)) {
    fs.rmSync(path.join(paths.testsDir, file), { recursive: true, force: true });
  }
  const testFiles = fs.readdirSync(PACKAGE_TESTS_DIR).filter(file => file.endsWith('.ts'));
  for (const file of testFiles) {
    fs.copyFileSync(path.join(PACKAGE_TESTS_DIR, file), path.join(paths.testsDir, file));
  }

  fs.writeFileSync(paths.configPath, renderPlaywrightConfig(config, projectRoot, env));

  return { ...paths, testFiles };
}

const HTMLVALIDATE_BASE_NAME = 'hugo-validator/configs/htmlvalidate';

/**
 * The site's .htmlvalidate.json with this package's base config merged in.
 *
 * html-validate resolves "extends" names from its OWN install location, not
 * from the config file. When html-validate lives inside this package (a
 * linked checkout, or a nested install) it cannot find "hugo-validator" by
 * name. Resolving the base here removes that dependency on node_modules layout.
 * Site rules win over base rules. Relative paths are made absolute because
 * the merged file lives in a different folder.
 */
function mergeHtmlValidateConfig(siteConfig, baseConfig, siteConfigDir) {
  const absolutize = (entry) =>
    typeof entry === 'string' && /^\.\.?\//.test(entry) ? path.resolve(siteConfigDir, entry) : entry;

  const siteExtends = (siteConfig.extends || []).filter(entry => entry !== HTMLVALIDATE_BASE_NAME);
  const usesBase = (siteConfig.extends || []).includes(HTMLVALIDATE_BASE_NAME);

  const merged = { ...siteConfig };
  merged.extends = [...(usesBase ? baseConfig.extends || [] : []), ...siteExtends.map(absolutize)];
  merged.rules = { ...(usesBase ? baseConfig.rules || {} : {}), ...(siteConfig.rules || {}) };
  for (const key of ['elements', 'plugins']) {
    if (Array.isArray(merged[key])) merged[key] = merged[key].map(absolutize);
  }
  // The merged file is complete: do not also pick up configs found near the HTML files
  merged.root = true;
  return merged;
}

/**
 * Write the merged html-validate config into .runtime and return its path
 * (relative to the site root, for the command line).
 */
function prepareHtmlValidateConfig(projectRoot = process.cwd()) {
  const siteConfigDir = path.join(projectRoot, VALIDATOR_DIR);
  const siteConfigPath = path.join(siteConfigDir, '.htmlvalidate.json');
  const baseConfig = require('../configs/htmlvalidate.base.js');

  let siteConfig = { extends: [HTMLVALIDATE_BASE_NAME] };
  if (fs.existsSync(siteConfigPath)) {
    siteConfig = JSON.parse(fs.readFileSync(siteConfigPath, 'utf8'));
  }

  const runtimeDir = path.join(projectRoot, RUNTIME_DIR);
  fs.mkdirSync(runtimeDir, { recursive: true });
  fs.writeFileSync(
    path.join(runtimeDir, 'htmlvalidate.json'),
    JSON.stringify(mergeHtmlValidateConfig(siteConfig, baseConfig, siteConfigDir), null, 2) + '\n'
  );
  return path.join(RUNTIME_DIR, 'htmlvalidate.json');
}

module.exports = {
  prepareRuntime,
  prepareHtmlValidateConfig,
  mergeHtmlValidateConfig,
  runtimePaths,
  renderPlaywrightConfig,
  resolveServerCommand,
  resolveBrowserExecutable,
  RUNTIME_DIR,
  PACKAGE_TESTS_DIR,
};
